//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDiary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientDiary.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string UIAdd {
            get {
                return ResourceManager.GetString("UIAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new client.
        /// </summary>
        public static string UIAddNewClient {
            get {
                return ResourceManager.GetString("UIAddNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new service.
        /// </summary>
        public static string UIAddNewService {
            get {
                return ResourceManager.GetString("UIAddNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Record.
        /// </summary>
        public static string UIAddRecord {
            get {
                return ResourceManager.GetString("UIAddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By hands.
        /// </summary>
        public static string UIByHands {
            get {
                return ResourceManager.GetString("UIByHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UICancel {
            get {
                return ResourceManager.GetString("UICancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string UIClient {
            get {
                return ResourceManager.GetString("UIClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string UIClients {
            get {
                return ResourceManager.GetString("UIClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From contacts.
        /// </summary>
        public static string UIFromContacts {
            get {
                return ResourceManager.GetString("UIFromContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new clent.
        /// </summary>
        public static string UIMesageAddNewClient {
            get {
                return ResourceManager.GetString("UIMesageAddNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new service.
        /// </summary>
        public static string UIMessageAddNewService {
            get {
                return ResourceManager.GetString("UIMessageAddNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t any clients.
        /// </summary>
        public static string UIMessageArentAnyClients {
            get {
                return ResourceManager.GetString("UIMessageArentAnyClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t any services.
        /// </summary>
        public static string UIMessageArentAnyServices {
            get {
                return ResourceManager.GetString("UIMessageArentAnyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new client info and press Ok.
        /// </summary>
        public static string UIMessageEnterClientInfo {
            get {
                return ResourceManager.GetString("UIMessageEnterClientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter service&apos;s info and press Ok.
        /// </summary>
        public static string UIMessageEnterServiceInfo {
            get {
                return ResourceManager.GetString("UIMessageEnterServiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to add a new client?.
        /// </summary>
        public static string UIMessageHowToAddNewClient {
            get {
                return ResourceManager.GetString("UIMessageHowToAddNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select services.
        /// </summary>
        public static string UIMessageSelectServices {
            get {
                return ResourceManager.GetString("UIMessageSelectServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UIName {
            get {
                return ResourceManager.GetString("UIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string UIPhone {
            get {
                return ResourceManager.GetString("UIPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string UIServices {
            get {
                return ResourceManager.GetString("UIServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services&apos;s name.
        /// </summary>
        public static string UIServicesName {
            get {
                return ResourceManager.GetString("UIServicesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service&apos;s price.
        /// </summary>
        public static string UIServicesPrice {
            get {
                return ResourceManager.GetString("UIServicesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string UISettings {
            get {
                return ResourceManager.GetString("UISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string UIStatistic {
            get {
                return ResourceManager.GetString("UIStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string UIWorkflow {
            get {
                return ResourceManager.GetString("UIWorkflow", resourceCulture);
            }
        }
    }
}
